const menu = [
  {
    id: 1,
    title: 'Uji-Special',
    category: 'breakfast',
    price: 800,
    img: './images/item-1.jpg',
    desc: `Often cooked or served with added flavourings such as sugar, honey, fruit or syrup to make a sweet cereal, `,
  },
  {
    id: 2,
    title: 'Samaki-Ugali',
    category: 'lunch',
    price: 2000,
    img: './images/Samaki.jpeg',
    desc: `For many Kenyans, Samaki-ugali along with a small amount of cooked vegetables or saucy stew is a normal meal`,
  },
  {
    id: 3,
    title: 'Mixer-Special',
    category: 'shakes',
    price: 1000,
    img: './images/Mixer.jpeg',
    desc: `Give your Mixer-Special an extra boost with the simplest ingredients.`,
  },
  {
    id: 4,
    title: 'Chai-Tangawizi',
    category: 'breakfast',
    price: 500,
    img: './images/Chaitangawizi.jpeg',
    desc: ` mixed with plenty of whole fat milk, and sweetened up with a few heaping tablespoons of sugar. `,
  },
  {
    id: 5,
    title: 'Matoke-Nyama',
    category: 'lunch',
    price: 1500,
    img: './images/Matokenyama.jpeg',
    desc: `I was in the mood to eat a popular Tanzanian food known as ndizi na nyama, or plantain bananas mixed with meat`,
  },
  {
    id: 6,
    title: 'Avacado-Shake',
    category: 'shakes',
    price: 8000,
    img: './images/Avacado-Shake.jpeg',
    desc: ` Give your Avacado-Shake an extra boost with the simplest ingredients.`,
  },
  {
    id: 7,
    title: 'Samosa-Chai',
    category: 'breakfast',
    price: 1000,
    img: './images/Samosa.jpeg',
    desc: `Samosas are small triangular pockets of spiced meat or vegetables put in a pastry wrapper and deep fried to a golden brown for ultimate enjoyment.`,
  },
  {
    id: 8,
    title: 'Chapati Chafua',
    category: 'lunch',
    price: 1200,
    img: './images/Chapati.jpeg',
    desc: `Chapatis go well with fried cabbage, beans, or even just rolled up with a cup of tea!`,
  },
  {
    id: 9,
    title: 'Berrys',
    category: 'shakes',
    price: 1500,
    img: './images/Berrys.jpeg',
    desc: ` Give your Berry smoothie an extra boost with the simplest ingredients.`,
  },
];
export default menu;
